#version: "3.9"

services:
  playwright_bot:
    build: .
    image: playwright-bot:latest
#    container_name: bot_1
    deploy:
      replicas: 5
      restart_policy:
        condition: any
    volumes:
      - ./screenshots:/app/screenshots
    environment:
      - TZ=UTC

volumes:
  screenshots: